### ISSUE TITLE
Disconnect errors

### ISSUE THREAD

**Issue by virtuald** [robotpy/pynetconsole#7]
Reported on the mailing list:

> Since updating to robotpy 2018 we've been seeing this message repeat in netconsole, every few seconds:
>
> ```
> Connecting to roborio-4096-frc.local:1741...OK
> .. connection dropped
> ```
>
> ...
>
> Yes, DS is connected at the time, driving the robot around.  Message pops up every 5 seconds on two robots running 2018 and two different DS laptops.  

It happens in wired and wireless environments.

**Comment by dbadb** [comment]
.. connection dropped
Connecting to 10.49.15.2:1741...OK
.. connection dropped
Connecting to 10.49.15.2:1741...OK
.. connection dropped
Connecting to 10.49.15.2:1741...OK
[147.97] stopping live window mode.
[147.98] NOTICE  disabled init
.. connection dropped
Connecting to 10.49.15.2:1741...OK
.. connection dropped


I wonder if this has something to do with https://github.com/wpilibsuite/allwpilib/issues/889?

**Comment by auscompgeek** [comment]
I think this is the opposite issue.

**Comment by virtuald** [comment]
I'm able to get this error to occur locally, I think it's a pynetconsole implementation bug. I hope to have a fix shortly.
